#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

/*
PROBLEM 2:
    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed
    four million, find the sum of the even-valued terms.
*/

//SOLUTION

bool isEven(int n){
    return (n % 2) == 0;
}

int sumLessThanMaxFibonacciNumbers(int max){
    int n0 = 0, n1 = 1, n = 0, sum = 0;
    while(n < max){
        n0 = n1;
        n1 = n;
        n = n0 + n1;
        sum += (isEven(n)) ? n:0;
    }
    return sum;
}

int main(){
    int n = 4000000;
    printf("Answer: %d", sumLessThanMaxFibonacciNumbers(n));
    return 0;
}


